### PR TITLE
December edits

### PR DESCRIPTION
**Pull request by zachhimes**

### CODE REVIEW

**Comment by balmas** [comment]
thanks @zachhimes  - will review this this week.

**Comment by lcerrato** [comment]
Some questions for my own reference:
are we keeping these tracking files?
should there be new URNs assigned to some of these?

**Comment by lcerrato** [comment]
A couple of general preliminary points:
1) I would not comment out the change log once it is has been marked up, and there is no need for the time stamp in the when attribute. I don't know how others feel, but if it's my call, I wouldn't bother with the time. 
2) Be aware of the lang attribute: it has been changed to three letters in the front matter but appears as two letters within the body itself.

**Comment by lcerrato** [comment]
Worked on phi0474.phi001 lat & eng
check https://github.com/PerseusDL/canonical-latinLit/pull/102 for list of suggested changes and revisions
the main thing I noticed was that there was no CTS structure in the text itself

**Comment by balmas** [comment]
@lcerrato agree no need to insist upon timestamp in the when attribute. In the files I converted, I just used a date without time (and if the old change long entry just had a month and year, I just used the first day of the month in the date stamp for the when attribute)

**Comment by lcerrato** [comment]
thanks @balmas 
I used the first day of the month, as well.
I also removed the revision x.x info, as there can be n number of the same ones, and the date stamp should clarify this info. Again, a preference.

**Comment by zachhimes** [comment]
@lcerrato For a date with only the year, should I just set the date to be January 1st of that year or just set it to be that year? Should the change log be removed instead of commented out?

**Comment by lcerrato** [comment]
Yes, just choose 01-01 if the year is the only thing included.
By all means, eliminate the old log if you are sure it's all been captured. If not, I will do so when I review the text.

**Pull request closed without merging**
