### PR TITLE
phi1348_take_two

### PR DESCRIPTION
**Pull request by AlisonBabeu**
hi @lcerrato continuing work on Suetonius started a while ago following guidelines of closed pull request and email. Updated cts_.xml, headers, and bibliographic metadata including new links.

Will continue sending in batches if these changes are acceptable.

### CODE REVIEW

**Review by lcerrato — APPROVED** [review]

**Comment by AlisonBabeu** [comment]
hi @lcerrato one more question, as I've gone through the ENglish files, in some cases the author's note was taken out and in others it was not. Should I just leave them as they are for the moment or would it be worth removing them, even though I am not sure what I would do with them....

**Comment by lcerrato** [comment]
@AlisonBabeu 
Can you give me an example of what you mean?

**Comment by lcerrato** [comment]
@AlisonBabeu 
These files need a comprehensive review as they were a part of the initial conversion process, so reviewing for content should probably be done within the larger context of bringing these up to the current best practice standards.

**Comment by lcerrato** [comment]
@AlisonBabeu 
Ok, I would have to do a deeper dive to see what else is missing from this markup.

**Pull request merged**
