### PR TITLE
Updated phi1351.phi004.perseus-lat1.xml

### PR DESCRIPTION
**Pull request by annettegessner**
we updated this file (Tacitus Historiae) to be CTS compliant

### CODE REVIEW

**Comment by PonteIneptique** [comment]
For the merge to be done you need to add the cts métadata files as well as bumping the URN. Otherwise it seems good

**Comment by annettegessner** [comment]
YES! Passes hook test now! B-)

**Comment by PonteIneptique** [comment]
I am gonna ask you a last thing:
- can you remove the \@subtype in the citationScheme
- can you use simple \ before div[@n="$2"] 

?

**Comment by annettegessner** [comment]
Like this?
(Still passing hook test.)

**Comment by PonteIneptique** [comment]
Perfect ! Merged !

**Pull request merged**
