### PR TITLE
(phi0474.phi030.perseus-lat1.xml) EpiDoc and CTS conversion

### PR DESCRIPTION
**Pull request by PonteIneptique**
4 to go ?

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |      0.1 |
| `nodes_count`   |     48   |
| `texts_passing` |      1   |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |    +4122 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi030/phi0474.phi030.perseus-lat1.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5262)*

**Review by mkonieczny9805 — APPROVED** [review]

**Comment by mkonieczny9805** [comment]
@lcerrato @PonteIneptique 
Can one use the `<sic>` tag for text enclosed in daggers?

**Comment by lcerrato** [comment]
Yes, I do that. † `<sic>`; < > `<add>`; [ ] `<del>` where applicable. There are some exceptions.

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |     0.09 |
| `nodes_count`   |    48    |
| `texts_passing` |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |    +4101 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi030/phi0474.phi030.perseus-lat1.xml` | Deleted  |
| `./data/phi0474/phi030/phi0474.phi030.perseus-lat2.xml` | New      |
| `./data/phi0474/phi030/phi0474.phi030.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5291)*

**Pull request merged**
