### PR TITLE
convert beta to unicode

### PR DESCRIPTION
**Pull request by balmas**

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4777)*

**Comment by lcerrato** [comment]
The colons were not converted and there was a stray 2 (probably a terminal sigma code). I've found these types of bad conversion errors scattered elsewhere.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4791)*

**Comment by balmas** [comment]
> The colons were not converted and there was a stray 2 (probably a terminal sigma code). I've found these types of bad conversion errors scattered elsewhere.

oops, sorry about that! I'm guessing these conversion errors all probably stem from the same source -- i used the xslt at https://github.com/PerseusDL/tei-conversion-tools/blob/master/xslt/alpheios/text-beta-uni.xsl  .

Should all : be converted to . when converting from beta to unicode? If so I can make that change to the transformation in case I or anyone else uses it again.

As for the 2, the original was this:

qeoi=s2

does s2 signify terminal sigma?  If so, I can make that change to the transformation too.

**Pull request merged**
