### PR TITLE
phi0134.phi002.perseus lat

### PR DESCRIPTION
**Pull request by lcerrato**

### CODE REVIEW

**Comment by lcerrato** [comment]
@balmas @TDBuck 
Would one of you please check and merge? I need an example for Zach's work to continue. 

Also note that this has implications for #53 as I added workgroup level cts file.

**Comment by balmas** [comment]
@lcerrato ah this exposes a limitation in the capitains test suite --- it found 9 lines so it passed, but there are many more than 9 ... the rest are enclosed in speaker tags.

I think it can be addressed by changing the refsDecl for the line level citation as follows, to have an extra `/` before the tei:l telling it to look anywhere inside the parent div.

```
replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2']//tei:l[@n='$3'])">
```

otherwise it looks good to me!

**Comment by lcerrato** [comment]
@balmas 
Thanks. This is one of the reasons I was hesitant about drama.

**Comment by lcerrato** [comment]
ok, this gives 1068 lines!

**Comment by balmas** [comment]
yay!

**Pull request merged**
