### PR TITLE
(phi0474.phi020.perseus-lat1.xml) EpiDoc and CTS conversion

### PR DESCRIPTION
**Pull request by PonteIneptique**
Here is the next step after 031 :)
I kept the indented p's, the section according to the choice of OLD, moved around the chapter where necessary, added the required information here and there.
I did not touch the header outside of capitains and change information.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |     0.09 |
| `nodes_count`   |   147    |
| `texts_passing` |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +15338 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi020/phi0474.phi020.perseus-lat1.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5235)*

**Comment by lcerrato** [comment]
@mkonieczny9805 
Yes, that's a valid tag.
As long as you work on the files on each branch, no conflicts should be introduced. If you work on the same file in separate branches without first pulling from master, then that would introduce conflicts.

**Comment by mkonieczny9805** [comment]
@lcerrato Got it, thanks!

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |     0.09 |
| `nodes_count`   |   147    |
| `texts_passing` |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +15314 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi020/phi0474.phi020.perseus-lat1.xml` | Deleted  |
| `./data/phi0474/phi020/phi0474.phi020.perseus-lat2.xml` | New      |
| `./data/phi0474/phi020/phi0474.phi020.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5242)*

**Review by mkonieczny9805 — APPROVED** [review]

**Comment by mkonieczny9805** [comment]
@lcerrato @PonteIneptique 
These files are ready to go; URN must be "bumped".

**Pull request merged**
