### PR TITLE
(typo-fixes) global subtitle cleanup

### PR DESCRIPTION
**Pull request by lcerrato**
collection wide cleanup of subtitles in keeping with https://github.com/PerseusDL/canonical-greekLit/issues/1322

### CODE REVIEW

**Comment by AlisonBabeu** [comment]
Hey @lcerrato this is a great idea.  Another one I think that could be globally removed is <editor role="editor"> and be
changed to <editor> only. Just a thought.

**Comment by lcerrato** [comment]
@AlisonBabeu Can you clarify what other one you are thinking of?

**Comment by AlisonBabeu** [comment]
You're going to laugh I forgot to actually put the xml in here.  I was thinking of globally changing 
`<editor role="editor">` to just `<editor>`.  Sorry.

**Comment by lcerrato** [comment]
@AlisonBabeu 
That's what I thought (missing markup tags)! 
Yes, those type of things should already be corrected as we convert but any mass global PR should focus on one item at time.

**Pull request merged**
