### PR TITLE
(phi0474.phi027.perseus-lat1.xml) CTS and EpiDoc conversion

### PR DESCRIPTION
**Pull request by PonteIneptique**
Hi there :) 
I needed the In Pisonem for my PhD, so here it is with a step by step.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     0.12 |
| `metadata_passing` |     1    |
| `metadata_total`   |     1    |
| `nodes_count`      |    42    |
| `texts_passing`    |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +10935 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi027/__cts__.xml`                     | New      |
| `./data/phi0474/phi027/__cts__.xml`                     | Passing  |
| `./data/phi0474/phi027/phi0474.phi027.perseus-lat1.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5207)*

**Comment by lcerrato** [comment]
@PonteIneptique 
Still looking at this. I have to bump it and bring the header into the most up to date conventions.
The containers we use for Cicero are the sections, not the chapters, so that needs a major revision.

**Comment by PonteIneptique** [comment]
> The containers we use for Cicero are the sections, not the chapters, so that needs a major revision.

Then I shall restart the work from the change part of things. Do you care rend about anything such as `<p rend="cont">` or should I just move from milestone section to div ? I'll do that tomorrow most probably

**Comment by lcerrato** [comment]
@PonteIneptique 
Hi, I've already made header changes and other formatting changes. We do some basic things like capture indents and so forth. So it would be better for me to finish this review for now. Otherwise we are just going to introduce conflicts I think.

**Comment by PonteIneptique** [comment]
Hmm, I would rather start from scratch than the other way around if you don't mind. Putting back the chapter into milestone and the section into div will be horrible to do. Worst case, I can copy your header to the file when I am done on the new branch... But I would not merge this if you want to have section :)

**Comment by lcerrato** [comment]
@PonteIneptique 
Actually, I've done it for other Cicero texts — my student did the same thing on earlier one so the changes were made then. This is fairly short. My changes are deeper than the header, such as indentation for ease of reading. Let me finish (since I've done a lot already) and then if you spot anything you can revise.
The problem with any file bumping is that we cannot easily diff.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     0.11 |
| `metadata_passing` |     1    |
| `metadata_total`   |     1    |
| `nodes_count`      |    42    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +10935 |

## Units

| Changed                             | Status   |
|:------------------------------------|:---------|
| `./data/phi0474/phi027/__cts__.xml` | New      |
| `./data/phi0474/phi027/__cts__.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5209)*

**Comment by lcerrato** [comment]
@PonteIneptique 
There were numerous incorrect breaks here — that's something we look out for during conversion. If there is no hard break, sometimes that means the sections or chapters were inserted incorrectly, and that's quite common in these Latin texts. Cicero was not always professionally entered, so there are many errors to look for.
There was also a little beta code and some quotation marks. I'll double check the word count to be sure that I have it right.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     0.14 |
| `metadata_passing` |     1    |
| `metadata_total`   |     1    |
| `nodes_count`      |   160    |
| `texts_passing`    |     1    |
| `texts_total`      |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +21857 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi027/__cts__.xml`                     | New      |
| `./data/phi0474/phi027/phi0474.phi027.perseus-lat2.xml` | New      |
| `./data/phi0474/phi027/__cts__.xml`                     | Passing  |
| `./data/phi0474/phi027/phi0474.phi027.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5211)*

**Comment by lcerrato** [comment]
Bumped URN and removed old files.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     0.12 |
| `metadata_passing` |     1    |
| `metadata_total`   |     1    |
| `nodes_count`      |   118    |
| `texts_passing`    |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +10922 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi027/__cts__.xml`                     | New      |
| `./data/phi0474/phi027/phi0474.phi027.perseus-lat1.xml` | Deleted  |
| `./data/phi0474/phi027/phi0474.phi027.perseus-lat2.xml` | New      |
| `./data/phi0474/phi027/__cts__.xml`                     | Passing  |
| `./data/phi0474/phi027/phi0474.phi027.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5213)*

**Pull request merged**
