### PR TITLE
use the work/edition title not the host title?

### PR DESCRIPTION
**Pull request by balmas**
Hi @lcerrato we're starting to go through some of the canonical texts for use with Alpheios. Will submit some PRs as we go. Let me know if you'd prefer that we just work in a fork and submit them in batches. Thanks :-)

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4774)*

**Comment by lcerrato** [comment]
@balmas 
Hi! PRs as you go work for me. I am still mainly working in the Greek texts but I have been doing a comprehensive review of headers, editions, etc. so if I notice issues there, I may pop in and correct as you submit. Thanks for the contributions!

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     -0.1 |
| `metadata_passing` |     -1   |
| `texts_passing`    |     -1   |

## Units

| Changed                                                     | Status   |
|:------------------------------------------------------------|:---------|
| `./data/stoa0045/stoa002/__cts__.xml`                       | Failing  |
| `./data/stoa0045/stoa002/stoa0045.stoa002.perseus-lat2.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4788)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4793)*

**Pull request merged**
