### PR TITLE
Epidoc changes

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |      2.2 |
| `texts_passing` |    265   |

## Units

| Changed                                                     | Status   |
|:------------------------------------------------------------|:---------|
| `./data/phi0119/phi001/phi0119.phi001.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi002/phi0119.phi002.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi002/phi0119.phi002.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi003/phi0119.phi003.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi003/phi0119.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi004/phi0119.phi004.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi005/phi0119.phi005.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi005/phi0119.phi005.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi006/phi0119.phi006.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi007/phi0119.phi007.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi007/phi0119.phi007.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi008/phi0119.phi008.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi008/phi0119.phi008.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi009/phi0119.phi009.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi009/phi0119.phi009.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi010/phi0119.phi010.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi010/phi0119.phi010.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi011/phi0119.phi011.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi011/phi0119.phi011.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi012/phi0119.phi012.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi012/phi0119.phi012.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi013/phi0119.phi013.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi014/phi0119.phi014.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi014/phi0119.phi014.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi015/phi0119.phi015.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi015/phi0119.phi015.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi016/phi0119.phi016.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi016/phi0119.phi016.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi017/phi0119.phi017.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi017/phi0119.phi017.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi018/phi0119.phi018.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi018/phi0119.phi018.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi019/phi0119.phi019.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi019/phi0119.phi019.perseus-lat2.xml`     | Passing  |
| `./data/phi0119/phi020/phi0119.phi020.perseus-eng2.xml`     | Passing  |
| `./data/phi0119/phi020/phi0119.phi020.perseus-lat2.xml`     | Passing  |
| `./data/phi0134/phi001/phi0134.phi001.perseus-eng2.xml`     | Passing  |
| `./data/phi0134/phi001/phi0134.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi0134/phi002/phi0134.phi002.perseus-eng2.xml`     | Passing  |
| `./data/phi0134/phi002/phi0134.phi002.perseus-lat2.xml`     | Passing  |
| `./data/phi0134/phi003/phi0134.phi003.perseus-eng2.xml`     | Passing  |
| `./data/phi0134/phi003/phi0134.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi0134/phi004/phi0134.phi004.perseus-eng2.xml`     | Passing  |
| `./data/phi0134/phi004/phi0134.phi004.perseus-lat2.xml`     | Passing  |
| `./data/phi0134/phi005/phi0134.phi005.perseus-eng2.xml`     | Passing  |
| `./data/phi0134/phi005/phi0134.phi005.perseus-lat2.xml`     | Passing  |
| `./data/phi0134/phi006/phi0134.phi006.perseus-eng2.xml`     | Passing  |
| `./data/phi0134/phi006/phi0134.phi006.perseus-lat2.xml`     | Passing  |
| `./data/phi0448/phi001/phi0448.phi001.perseus-eng2.xml`     | Passing  |
| `./data/phi0448/phi001/phi0448.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi0472/phi001/phi0472.phi001.perseus-eng3.xml`     | Passing  |
| `./data/phi0472/phi001/phi0472.phi001.perseus-eng4.xml`     | Passing  |
| `./data/phi0478/phi003/phi0478.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo001/phi0588.abo001.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo002/phi0588.abo002.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo003/phi0588.abo003.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo004/phi0588.abo004.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo005/phi0588.abo005.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo006/phi0588.abo006.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo007/phi0588.abo007.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo008/phi0588.abo008.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo009/phi0588.abo009.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo010/phi0588.abo010.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo011/phi0588.abo011.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo012/phi0588.abo012.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo013/phi0588.abo013.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo014/phi0588.abo014.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo015/phi0588.abo015.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo016/phi0588.abo016.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo017/phi0588.abo017.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo018/phi0588.abo018.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo019/phi0588.abo019.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo020/phi0588.abo020.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo021/phi0588.abo021.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo022/phi0588.abo022.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo023/phi0588.abo023.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo024/phi0588.abo024.perseus-lat2.xml`     | Passing  |
| `./data/phi0588/abo025/phi0588.abo025.perseus-lat2.xml`     | Passing  |
| `./data/phi0631/phi001/phi0631.phi001.perseus-eng2.xml`     | Passing  |
| `./data/phi0631/phi001/phi0631.phi001.perseus-lat3.xml`     | Passing  |
| `./data/phi0631/phi002/phi0631.phi002.perseus-lat3.xml`     | Passing  |
| `./data/phi0631/phi003/phi0631.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi0660/phi003/phi0660.phi003.perseus-eng2.xml`     | Passing  |
| `./data/phi0660/phi003/phi0660.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi0690/phi001/phi0690.phi001.perseus-eng2.xml`     | Passing  |
| `./data/phi0690/phi001/phi0690.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi0690/phi002/phi0690.phi002.perseus-eng2.xml`     | Passing  |
| `./data/phi0690/phi003/phi0690.phi003.perseus-eng2.xml`     | Passing  |
| `./data/phi0690/phi003/phi0690.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi0836/phi002/phi0836.phi002.perseus-lat6.xml`     | Passing  |
| `./data/phi0845/phi002/phi0845.phi002.perseus-lat3.xml`     | Passing  |
| `./data/phi0860/phi001/phi0860.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi0893/phi001/phi0893.phi001.perseus-eng2.xml`     | Passing  |
| `./data/phi0893/phi001/phi0893.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi0893/phi003/phi0893.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi0893/phi004/phi0893.phi004.perseus-eng2.xml`     | Passing  |
| `./data/phi0893/phi004/phi0893.phi004.perseus-lat2.xml`     | Passing  |
| `./data/phi0893/phi005/phi0893.phi005.perseus-lat2.xml`     | Passing  |
| `./data/phi0893/phi006/phi0893.phi006.perseus-eng2.xml`     | Passing  |
| `./data/phi0893/phi006/phi0893.phi006.perseus-lat2.xml`     | Passing  |
| `./data/phi0914/phi001/phi0914.phi001.perseus-eng3.xml`     | Passing  |
| `./data/phi0917/phi001/phi0917.phi001.perseus-eng2.xml`     | Passing  |
| `./data/phi0959/phi001/phi0959.phi001.perseus-eng2.xml`     | Passing  |
| `./data/phi0959/phi001/phi0959.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi0959/phi002/phi0959.phi002.perseus-eng2.xml`     | Passing  |
| `./data/phi0959/phi002/phi0959.phi002.perseus-lat2.xml`     | Passing  |
| `./data/phi0959/phi003/phi0959.phi003.perseus-eng2.xml`     | Passing  |
| `./data/phi0959/phi003/phi0959.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi0959/phi004/phi0959.phi004.perseus-eng2.xml`     | Passing  |
| `./data/phi0959/phi004/phi0959.phi004.perseus-lat2.xml`     | Passing  |
| `./data/phi0959/phi005/phi0959.phi005.perseus-eng2.xml`     | Passing  |
| `./data/phi0959/phi005/phi0959.phi005.perseus-lat2.xml`     | Passing  |
| `./data/phi0959/phi006/phi0959.phi006.perseus-eng3.xml`     | Passing  |
| `./data/phi0959/phi006/phi0959.phi006.perseus-eng4.xml`     | Passing  |
| `./data/phi0959/phi006/phi0959.phi006.perseus-lat2.xml`     | Passing  |
| `./data/phi0959/phi009/phi0959.phi009.perseus-lat2.xml`     | Passing  |
| `./data/phi1014/phi001/phi1014.phi001.perseus-lat1.xml`     | Passing  |
| `./data/phi1017/phi001/phi1017.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi002/phi1017.phi002.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi003/phi1017.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi004/phi1017.phi004.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi005/phi1017.phi005.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi006/phi1017.phi006.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi007/phi1017.phi007.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi008/phi1017.phi008.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi009/phi1017.phi009.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi010/phi1017.phi010.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi011/phi1017.phi011.perseus-eng2.xml`     | Passing  |
| `./data/phi1017/phi011/phi1017.phi011.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi013/phi1017.phi013.perseus-lat2.xml`     | Passing  |
| `./data/phi1017/phi014/phi1017.phi014.perseus-lat2.xml`     | Passing  |
| `./data/phi1020/phi003/phi1020.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi1035/phi001/phi1035.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi1056/phi001/phi1056.phi001.perseus-eng1.xml`     | Passing  |
| `./data/phi1056/phi001/phi1056.phi001.perseus-lat1.xml`     | Passing  |
| `./data/phi1254/phi001/phi1254.phi001.perseus-eng1.xml`     | Passing  |
| `./data/phi1254/phi001/phi1254.phi001.perseus-lat1.xml`     | Passing  |
| `./data/phi1276/phi001/phi1276.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi1294/phi002/phi1294.phi002.perseus-lat2.xml`     | Passing  |
| `./data/phi1318/phi001/phi1318.phi001.perseus-lat1.xml`     | Passing  |
| `./data/phi1345/phi001/phi1345.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo011/phi1348.abo011.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo011/phi1348.abo011.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo012/phi1348.abo012.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo012/phi1348.abo012.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo013/phi1348.abo013.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo013/phi1348.abo013.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo014/phi1348.abo014.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo014/phi1348.abo014.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo015/phi1348.abo015.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo015/phi1348.abo015.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo016/phi1348.abo016.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo016/phi1348.abo016.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo017/phi1348.abo017.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo017/phi1348.abo017.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo018/phi1348.abo018.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo018/phi1348.abo018.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo019/phi1348.abo019.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo019/phi1348.abo019.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo020/phi1348.abo020.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo020/phi1348.abo020.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo021/phi1348.abo021.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo021/phi1348.abo021.perseus-lat2.xml`     | Passing  |
| `./data/phi1348/abo022/phi1348.abo022.perseus-eng2.xml`     | Passing  |
| `./data/phi1348/abo022/phi1348.abo022.perseus-lat2.xml`     | Passing  |
| `./data/phi1351/phi001/phi1351.phi001.perseus-lat1.xml`     | Passing  |
| `./data/phi1351/phi002/phi1351.phi002.perseus-lat1.xml`     | Passing  |
| `./data/phi2331/phi001/phi2331.phi001.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi002/phi2331.phi002.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi003/phi2331.phi003.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi004/phi2331.phi004.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi005/phi2331.phi005.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi006/phi2331.phi006.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi007/phi2331.phi007.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi008/phi2331.phi008.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi009/phi2331.phi009.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi010/phi2331.phi010.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi011/phi2331.phi011.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi012/phi2331.phi012.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi013/phi2331.phi013.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi014/phi2331.phi014.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi015/phi2331.phi015.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi016/phi2331.phi016.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi017/phi2331.phi017.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi018/phi2331.phi018.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi019/phi2331.phi019.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi020/phi2331.phi020.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi021/phi2331.phi021.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi022/phi2331.phi022.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi023/phi2331.phi023.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi024/phi2331.phi024.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi025/phi2331.phi025.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi026/phi2331.phi026.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi027/phi2331.phi027.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi028/phi2331.phi028.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi029/phi2331.phi029.perseus-lat2.xml`     | Passing  |
| `./data/phi2331/phi030/phi2331.phi030.perseus-lat2.xml`     | Passing  |
| `./data/stoa0023/stoa001/stoa0023.stoa001.perseus-eng1.xml` | Passing  |
| `./data/stoa0023/stoa001/stoa0023.stoa001.perseus-lat1.xml` | Passing  |
| `./data/stoa0045/stoa001/stoa0045.stoa001.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa002/stoa0045.stoa002.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa003/stoa0045.stoa003.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa004/stoa0045.stoa004.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa005/stoa0045.stoa005.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa006/stoa0045.stoa006.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa007/stoa0045.stoa007.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa008/stoa0045.stoa008.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa009/stoa0045.stoa009.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa010/stoa0045.stoa010.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa011/stoa0045.stoa011.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa012/stoa0045.stoa012.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa013/stoa0045.stoa013.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa014/stoa0045.stoa014.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa015/stoa0045.stoa015.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa016/stoa0045.stoa016.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa018/stoa0045.stoa018.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa019/stoa0045.stoa019.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa020/stoa0045.stoa020.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa021/stoa0045.stoa021.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa022/stoa0045.stoa022.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa025/stoa0045.stoa025.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa026/stoa0045.stoa026.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa027/stoa0045.stoa027.perseus-lat2.xml` | Passing  |
| `./data/stoa0045/stoa028/stoa0045.stoa028.perseus-lat2.xml` | Passing  |
| `./data/stoa0058/stoa001/stoa0058.stoa001.perseus-lat2.xml` | Passing  |
| `./data/stoa0058/stoa003/stoa0058.stoa003.perseus-lat1.xml` | Passing  |
| `./data/stoa0058/stoa006/stoa0058.stoa006.perseus-lat1.xml` | Passing  |
| `./data/stoa0058/stoa023/stoa0058.stoa023.perseus-lat1.xml` | Passing  |
| `./data/stoa0058/stoa025/stoa0058.stoa025.perseus-lat1.xml` | Passing  |
| `./data/stoa0058/stoa028/stoa0058.stoa028.perseus-lat1.xml` | Passing  |
| `./data/stoa0089/stoa001/stoa0089.stoa001.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa002/stoa0089.stoa002.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa003/stoa0089.stoa003.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa004/stoa0089.stoa004.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa005/stoa0089.stoa005.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa006/stoa0089.stoa006.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa007/stoa0089.stoa007.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa008/stoa0089.stoa008.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa009/stoa0089.stoa009.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa010/stoa0089.stoa010.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa011/stoa0089.stoa011.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa012/stoa0089.stoa012.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa013/stoa0089.stoa013.perseus-lat2.xml` | Passing  |
| `./data/stoa0089/stoa014/stoa0089.stoa014.perseus-lat2.xml` | Passing  |
| `./data/stoa0162/stoa004/stoa0162.stoa004.perseus-lat2.xml` | Passing  |
| `./data/stoa0203/stoa001/stoa0203.stoa001.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa001/stoa0238.stoa001.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa002/stoa0238.stoa002.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa003/stoa0238.stoa003.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa004/stoa0238.stoa004.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa005/stoa0238.stoa005.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa006/stoa0238.stoa006.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa007/stoa0238.stoa007.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa008/stoa0238.stoa008.perseus-lat2.xml` | Passing  |
| `./data/stoa0238/stoa009/stoa0238.stoa009.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa004/stoa0255.stoa004.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa006/stoa0255.stoa006.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa007/stoa0255.stoa007.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa008/stoa0255.stoa008.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa009/stoa0255.stoa009.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa010/stoa0255.stoa010.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa011/stoa0255.stoa011.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa012/stoa0255.stoa012.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa013/stoa0255.stoa013.perseus-lat2.xml` | Passing  |
| `./data/stoa0255/stoa014/stoa0255.stoa014.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/2214)*

**Comment by lcerrato** [comment]
@sonofmun This build keeps failing:
https://travis-ci.org/PerseusDL/canonical-latinLit/builds/265295544

**Comment by sonofmun** [comment]
Hmm. This is a problem with creating the text files. I will see if I can recreate it locally and figure out how to correct it.

**Comment by sonofmun** [comment]
@lcerrato It looks like this file has never been extracted to text. Check https://travis-ci.org/PerseusDL/canonical-latinLit/builds/246118354. That was right after we implemented the text extraction. There is a problem with that file that does not jive with our text extraction method. I will take a closer look and see if I can figure out what is going on.

**Comment by sonofmun** [comment]
PR #225 is a temporary fix since that was the file that was causing the error.

**Pull request merged**
