### PR TITLE
Phi0448.phi001

### LINKED ISSUE #55: convert phi0448.phi001.perseus-lat1.xml
convert phi0448.phi001.perseus-lat1.xml

### PR DESCRIPTION
**Pull request by lcerrato**
fix #55

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Hi @lcerrato,
The conversion is super great. There has been an update to the guide: basically, the old \\w is now \w and \'$1\' is just $1. This was something we were "forced" to do back at the beginning of my dev but not anymore :)
Otherwise, ready to merge :')

**Comment by lcerrato** [comment]
Hi @PonteIneptique 
Could you clarify further? I get the "\'$1\' is just $1" part but not the "the old \w is now \w"

otherwise, I'd prefer you merge this PR and make the changes so that I can see an example of what you mean.

refsDecl are not my thing: I really need examples to understand them better.

**Comment by lcerrato** [comment]
ok, so I see in phi0914.phi001.perseus-eng3.xml
that there is one forward slash before w+ and $1 (etc) is not escaped.

That means that the wiki example 
https://raw.githubusercontent.com/PerseusDL/canonical-greekLit/master/data/tlg0003/tlg001/tlg0003.tlg001.perseus-eng6.xml

is wrong. Looks like other files have the same issue.

**Comment by PonteIneptique** [comment]
Hmm, I never refer to the wiki, which led me not to think about it as outdated. That might have been why we did not understand each other...
My comment on github was understood has escaped, making `\\w` looking as `\w`. Did not see that

**Pull request closed without merging**
