### PR TITLE
(phi0969) Capitains + Metadata. Not bumped

### PR DESCRIPTION
**Pull request by PonteIneptique**
Hi @lcerrato :)
Here is a first PR for Persius. Let me know if this is okay so that I can bump it :)

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     0.07 |
| `metadata_passing` |     1    |
| `metadata_total`   |     2    |
| `nodes_count`      |   656    |

## Words

| Changed   | Status   |
|:----------|:---------|
| `UNK`     | New      |

## Units

| Changed                             | Status   |
|:------------------------------------|:---------|
| `./data/phi0969/__cts__.xml`        | New      |
| `./data/phi0969/phi001/__cts__.xml` | New      |
| `./data/phi0969/__cts__.xml`        | Passing  |
| `./data/phi0969/phi001/__cts__.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4488)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     0.14 |
| `metadata_passing` |     2    |
| `metadata_total`   |     2    |
| `nodes_count`      |   656    |
| `texts_passing`    |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |    +4537 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0969/__cts__.xml`                            | New      |
| `./data/phi0969/phi001/__cts__.xml`                     | New      |
| `./data/phi0969/__cts__.xml`                            | Passing  |
| `./data/phi0969/phi001/__cts__.xml`                     | Passing  |
| `./data/phi0969/phi001/phi0969.phi001.perseus-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4490)*

**Comment by PonteIneptique** [comment]
Hi @lcerrato, is the PR okay with you ?

**Comment by lcerrato** [comment]
Hi @PonteIneptique 
Sorry, I have not had the time to review this!

**Comment by lcerrato** [comment]
fixed via #272

**Pull request closed without merging**
