### PR TITLE
(0893.002.lat1) CTS and Epidoc

### PR DESCRIPTION
**Pull request by zachhimes**

### CODE REVIEW

**Comment by PonteIneptique** [comment]
My old commit just missed the __cts__.xml files

**Comment by lcerrato** [comment]
Is there some action required here? I don't follow whose commit this is.

**Comment by zachhimes** [comment]
I think I messed up on the pull request. I apologize for the confusion.

**Comment by lcerrato** [comment]
@zachhimes no problem. Let me know if you have questions or concerns.

**Pull request merged**
