### PR TITLE
Create phi0690.phi003.perseus-lat2.xml

### PR DESCRIPTION
**Pull request by zachhimes**
Converted phi0690.phi003.perseus-lat1.xml to make it CTS/EpiDoc compliant.

### CODE REVIEW

**Comment by balmas** [comment]
Hi @zachhimes thanks for this! One comment -- I think the approach we want to take for converting the files is documented here: https://github.com/PerseusDL/tei-conversion-tools/wiki/Assigning-and-Updating-URNs  .. i.e. in order to be able to more easily check the changes, we want to make them in the existing file and then rename it at the end.  As we are trying to validate the documentation right now, if this process wasn't clear, from the documentation, we should fix that .. can you clarify which steps you were following here?

**Comment by zachhimes** [comment]
Hi @balmas , since I was updating phi0690.phi003.perseus-lat1.xmlI to P5/Epidoc/CTS, I thought that  it was my responsibility to reserve a new URN for the edition and rename the file to reflect this (I believe I tried to reserve a new URN using the form). I was following step 6 in the Workflows and Script Sequencing for Editors page: https://github.com/PerseusDL/tei-conversion-tools/wiki/Workflows-and-Script-Sequencing-for-Editors .

**Comment by balmas** [comment]
Ok, maybe this needs to be clarified further in the documentation then.  Step 6 links to this page:

**Comment by balmas** [comment]
Ok, maybe this needs to be clarified further in the documentation then.  Step 6 links to this page:

https://github.com/PerseusDL/tei-conversion-tools/wiki/Assigning-and-Updating-URNs
And Under the Long Version section there we have:

"The current policy when updating a text to CTS/EpiDoc compliance is to make those edits in the same file, tracked by Git. 

After completing edits, reserve a new URN for the edition using the form designed for the Perseus Catalog."

So, my expectation, if these directions are followed would be that the commit history in the pull request would include commits on the original file which show the CTS-epidoc changes, followed by a commit which renames the file.  But in your pull request I see only the new file, and the changes on it.  Is the difference clear?

**Comment by zachhimes** [comment]
The difference is clear. I think I forgot that instruction in the Long Version section of the Assigning and Updating URNs page because I was trying to follow the instructions in the Workflows and Script Sequencing for Editors page and I overlooked it by accident.

**Comment by balmas** [comment]
ok. then in this case, before I approve the pull request, can you please make the change to delete the prior version of this file from your branch? And confirm whether or not you did reserve the urn for the new version?  Thanks!

**Comment by zachhimes** [comment]
I deleted the prior version of the file from my branch. I cannot confirm whether I actually reserved the urn for the new version. When I tried to reserve a urn, I believe I didn't need to log onto the Perseus catalog server and now I do  (I don't know how to log onto the server).

**Comment by balmas** [comment]
@zachhimes I merged the pull request but a few things remain doing:
- [] your removal of the old file didn't make it to the pull request, I think maybe you forgot to push?
- [] the tracking.json file needs to be updated, using the tracking.py script.  Please let me know if the instructions on how to use this aren't yet clear.
Thanks!

**Comment by srdee** [comment]
The Tracking instructions aren't yet clear, so @zachhimes feel free to hold off on that--I'll try to get to those today or tomorrow, and notify you here when I do. When you do use the script, you'll actually want to use tracking-for-editors.py: [https://github.com/PerseusDL/tei-conversion-tools/blob/master/python/tracking-for-editors.py](https://github.com/PerseusDL/tei-conversion-tools/blob/master/python/tracking-for-editors.py)

@annakrohn sent out an email awhile back about how to log into the Catalog server--I'll try to dig it up, unless she gets to this first. You're right, that's a recent update.

**Comment by srdee** [comment]
Ok, @zachhimes and @balmas , the tracking script for editors should be good to go, with instructions here: https://github.com/PerseusDL/tei-conversion-tools/wiki/Tracking-Data

**Comment by zachhimes** [comment]
Hey @srdee , I tried to follow the instructions of the Tracking Data page. At step three (run in the command line: call('curl -O http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng', shell=True) ")     ), I get the following error: bash: syntax error near unexpected token `'curl -O http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng', . Do know why I am getting this error?

**Comment by srdee** [comment]
@zachhimes try just running: `curl -0 http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng`

--let me know if that works! If so, I'll update the instructions accordingly.

**Comment by srdee** [comment]
Oh! You'll also need [Jing](http://www.thaiopensource.com/relaxng/jing.html) and [Parallel](http://www.gnu.org/software/parallel/) installed for the EpiDoc checks to run. Are you using a  Mac? 

If so, I'd recommend installing [Homebrew](http://brew.sh/), if you haven't already, and then running `brew install jing` and `brew install parallel` from the command line. 

If you're not on Mac, the websites are linked above for the install.

**Comment by srdee** [comment]
Again, I'll add then notes above to the Wiki instructions after I'm sure you've got it working.

**Comment by zachhimes** [comment]
@srdee the new command works. Thanks!

**Comment by srdee** [comment]
Yay! I'll update the instructions

**Comment by srdee** [comment]
Instructions updated! https://github.com/PerseusDL/tei-conversion-tools/wiki/Tracking-Data

**Pull request merged**
