### PR TITLE
work title not host title

### PR DESCRIPTION
**Pull request by balmas**

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4783)*

**Comment by lcerrato** [comment]
see also https://github.com/PerseusDL/catalog_data/issues/166

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4801)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4803)*

**Pull request merged**
