### PR TITLE
Changes for new build

### PR DESCRIPTION
**Pull request by sonofmun**
Do not merge until Bridget has updated the Perseids servers.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/1142)*

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.01 |
| `texts_passing` |    -1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `UNK`     |   +53357 |
| `lat`     |   -53357 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0917/phi001/phi0917.phi001.perseus-lat2.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/1250)*

**Comment by sonofmun** [comment]
@lcerrato Once this passes Travis, this is ready to merge.

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.01 |
| `texts_passing` |    -1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `UNK`     |   +53357 |
| `lat`     |   -53357 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0917/phi001/phi0917.phi001.perseus-lat2.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/1272)*

**Pull request merged**
