### PR TITLE
(phi0474.phi021.perseus-lat1.xml) EpiDoc and CTS conversion

### PR DESCRIPTION
**Pull request by PonteIneptique**
And another one because I was afraid one was not enough :D

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |     0.09 |
| `nodes_count`   |    63    |
| `texts_passing` |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |    +7588 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi021/phi0474.phi021.perseus-lat1.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5241)*

**Comment by lcerrato** [comment]
FYI I change the names of these issues as there is only one specific file being converted. Using phi0474.phi021 implies the whole batch is being converted, but it is not.

**Comment by PonteIneptique** [comment]
My bad @lcerrato ! I'll do that for the next one !

**Review by mkonieczny9805 — APPROVED** [review]

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |     0.09 |
| `nodes_count`   |    63    |
| `texts_passing` |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |    +7586 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi021/phi0474.phi021.perseus-lat1.xml` | Deleted  |
| `./data/phi0474/phi021/phi0474.phi021.perseus-lat2.xml` | New      |
| `./data/phi0474/phi021/phi0474.phi021.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5248)*

**Pull request merged**
