### PR TITLE
Added a missing value to an n attribute

### PR DESCRIPTION
**Pull request by sonofmun**
This is the reason that the text was causing the build to fail

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Damn, that might be a miss from HookTest. Nice catch @sonofmun !

**Comment by sonofmun** [comment]
Adding an issue to Hooktest right now.

**Comment by sonofmun** [comment]
See Issue #243

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4171)*

**Comment by lcerrato** [comment]
Wow. Yes, that seems like something Hook should catch! Awesome work. This is so helpful. Sorry for the imposition @sonofmun

**Pull request merged**
