### PR TITLE
Phi0978.phi001.perseus-lat2 (initially opp-lat8)

### PR DESCRIPTION
**Pull request by annettegessner**
added new version in Epidoc, CTS-ready, passing hook test

### CODE REVIEW

**Comment by PonteIneptique** [comment]
@AlisonBabeu and @lcerrato , do you mind if I let the choice to you on this one ?

**Comment by lcerrato** [comment]
@PonteIneptique I'm not sure I'm following you.
I don't think this pertains to @AlisonBabeu 
@TDBuck and @balmas and I may need to revisit the workflow -- I don't think we can handle the OPP side of things presently.

**Comment by PonteIneptique** [comment]
@lcerrato I have to say I am always lost when it comes to who is responsible for new URNs :/ Would be good to make the workflow clearly for that.

**Comment by balmas** [comment]
The workflow called for the people doing the text conversion work to reserve the URNs.  We can revisit that if we would like stronger control on this.

**Comment by lcerrato** [comment]
I think we want senior members of the working group reserving the URNs and contributors such as students requesting this be done on their behalf. 
I don't know if we want Perseus doing so for OPP (or vice versa) but if we do we should clarify.

(I didn't realize that a new URN request was part of this particular PR, though, so that's why I asked.)

**Comment by balmas** [comment]
My opinion is that OPP staff should reserve the URNs themselves and it should be a requirement for a PR for a converted text. That was the whole point of making the form available, so that we could keep these things in sync.

**Comment by annettegessner** [comment]
Hi guys! 
When in need of a new work_ID, all I have been doing up until now with CSEL and PL opp-lat files has been asking @AlisonBabeu , what work_ID to use (mostly using our spreadsheets) and that's about it.
You can read my thoughts about the URN in issue #99 , where I suggest either pers2 or opp-lat8.

**Comment by lcerrato** [comment]
We're working towards a more generalized workflow. 
When you need to "bump" a URN, the form is linked from here:
https://github.com/PerseusDL/tei-conversion-tools/wiki/Assigning-and-Updating-URNs

**Comment by annettegessner** [comment]
Thanks for the link, @lcerrato , but following the link to the form, I am supposed to provide authentification and my Tufts-password doesn't work.

**Comment by annettegessner** [comment]
Thanks @balmas ! So opp-lat8 is taken! So (and since this is a new version of Mayhoff anyway) I am going to go with perseus-lat2. Changing the files now, so the pull request is up to date.

**Comment by lcerrato** [comment]
Would you mind adding a change header to reflect the new version and the changes you made?

**Comment by lcerrato** [comment]
@annettegessner Here's a suggestion:

` <revisionDesc>`
      
`     <change when="2016-02-19" who="Lisa Cerrato">CTS and EpiDoc conversion</change>`

`</revisionDesc>`

**Comment by annettegessner** [comment]
change header added - still passing hook test

**Comment by lcerrato** [comment]
Hi @annettegessner 
I don't see any text after the cRefPattern referring to what the pointer pattern extracts.

`<cRefPattern n="Chapter" ... >`
     `<p>This pointer pattern extracts Book and Chapter</p>`
        `</cRefPattern>`

or a refsDecl with the refState declared.
`<refState unit="n"/>`

Please check with @PonteIneptique as to whether these are required.

**Comment by annettegessner** [comment]
I am pretty sure, those informations are not necessarily required since we didn't use them in our CSEL files.

**Comment by PonteIneptique** [comment]
Technically not required, but recommended :')

**Comment by lcerrato** [comment]
I think, in the future, if you are using the perseus-lat2 name then you should follow the Perseus text examples. 

If you want to follow CSEL practices, then I would rename the file as opp-lat.

This isn't something we discussed or documented, so I'm just making a suggestion as to how best to move forward and sort this out in the future.

**Comment by annettegessner** [comment]
I added the description for the refsDecl.
In the second line of the XML I also changed the xml-models according to the Perseus documents.
Document still passing hook test.

**Comment by PonteIneptique** [comment]
I am okay with merging it . @lcerrato  ?

**Comment by lcerrato** [comment]
Thank you!

**Pull request merged**
