### PR TITLE
(0975.001.lat1) Convert to Capitains

### LINKED ISSUE #246: (0975.001) Convert Fabulae Aesopiae to Capitains

### PR DESCRIPTION
**Pull request by PonteIneptique**
Fix #246

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     0.14 |
| `metadata_passing` |     2    |
| `metadata_total`   |     2    |
| `nodes_count`      |  2083    |
| `texts_passing`    |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +11573 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0975/__cts__.xml`                            | New      |
| `./data/phi0975/phi001/__cts__.xml`                     | New      |
| `./data/phi0975/phi001/phi0975.phi001.perseus-lat1.xml` | Deleted  |
| `./data/phi0975/phi001/phi0975.phi001.perseus-lat2.xml` | New      |
| `./data/phi0975/__cts__.xml`                            | Passing  |
| `./data/phi0975/phi001/__cts__.xml`                     | Passing  |
| `./data/phi0975/phi001/phi0975.phi001.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4229)*

**Comment by lcerrato** [comment]
@PonteIneptique 
When you say bumped URN, you mean you changed the file name only, correct? 
We typically use this term to indicate the new URN was created in the CITE collections and I don't see one there so I am just checking if I need to do that.

**Comment by PonteIneptique** [comment]
Yes, I only updated the filename I did not change things in the catalog (not being part of the Perseusverse anymore I did not feel like I may :) )

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |     0.14 |
| `metadata_passing` |     2    |
| `metadata_total`   |     2    |
| `nodes_count`      |  2083    |
| `texts_passing`    |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +11573 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0975/__cts__.xml`                            | New      |
| `./data/phi0975/phi001/__cts__.xml`                     | New      |
| `./data/phi0975/phi001/phi0975.phi001.perseus-lat1.xml` | Deleted  |
| `./data/phi0975/phi001/phi0975.phi001.perseus-lat2.xml` | New      |
| `./data/phi0975/__cts__.xml`                            | Passing  |
| `./data/phi0975/phi001/__cts__.xml`                     | Passing  |
| `./data/phi0975/phi001/phi0975.phi001.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4237)*

**Comment by lcerrato** [comment]
Thank you, @PonteIneptique !

**Pull request merged**
