### PR TITLE
use work title not host title

### PR DESCRIPTION
**Pull request by balmas**

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4778)*

**Comment by lcerrato** [comment]
@balmas 
The way I have been regularizing labels is that the label for each edition or translation should match the book page for that work. Alternate titles are titles not labels.

**Comment by balmas** [comment]
ok, not sure I totally understand that, but if you don't agree with what I suggest here please feel free to reject it :-)

**Comment by lcerrato** [comment]
@balmas No problem. I am finding key biblio data is missing — like edition publishers and years and seeing info better suited to the catalog, like birth/death years. Just trying to provide consistent, brief info so that the user can immediately and briefly identify the source of the edition and doing it in a way that is as consistent as I can.

**Comment by lcerrato** [comment]
note: I really dislike the Latin label here — I've never seen commonly used (Sermones is better).

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-latinLit/4800)*

**Pull request merged**
