### PR TITLE
(phi0474.phi028.perseus-lat1.xml) EpiDoc and CTS conversion

### PR DESCRIPTION
**Pull request by PonteIneptique**
6 to go.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |      0.1 |
| `nodes_count`   |    104   |
| `texts_passing` |      1   |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +11809 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi028/phi0474.phi028.perseus-lat1.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5258)*

**Comment by mkonieczny9805** [comment]
Can anyone find a link to a full-text view of this volume:
https://archive.org/details/orationes0006cice/page/n5/mode/2up

I can borrow it for the purpose of checking the section breaks, but can we use this as the link for the source target?

These Cicero OCTs are really confusing. I guess there are two different editions, with the works distributed variously across the volumes in each edition. So, for example, we have the "volume 6" above with Pro Plancio etc., but there's also another "volume 6" containing Pro Milone which we used for phi031. Ugh.

**Comment by PonteIneptique** [comment]
Have you looked over at Hathi trust ? https://www.hathitrust.org/
It's bad for European customers but I expect it to work better for you ;)

**Comment by mkonieczny9805** [comment]
@PonteIneptique Yes I looked through all the Cicero OCTs on there, no luck unfortunately...

**Review by mkonieczny9805 — APPROVED** [review]

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |     0.09 |
| `nodes_count`   |   104    |
| `texts_passing` |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +11797 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi028/phi0474.phi028.perseus-lat1.xml` | Deleted  |
| `./data/phi0474/phi028/phi0474.phi028.perseus-lat2.xml` | New      |
| `./data/phi0474/phi028/phi0474.phi028.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5287)*

**Comment by AlisonBabeu** [comment]
Hi @mkonieczny9805 and @PonteIneptique, I remember how awful it was to catalog these volumes and I'm pretty sure a lot of the header info is wrong. You are quite right in that the works and how they were included in the volumes was different between the two editions.  I think this is a full view copy of the first edition of the book you list above here: 
https://babel.hathitrust.org/cgi/pt?id=njp.32101073249417 
This is the volume I used to create a catalog record for this work in Perseus but strangely the Hathi Trust catalog record insists that it is volume 5!

**Comment by lcerrato** [comment]
I saw this when creating CTS files. I recommend the borrow/only version to match the header. I checked this when creating the metadata and we do it elsewhere. So whatever best matches the new CTS files is best. If that is borrow only that’s fine.
Otherwise I believe all of the volumes will be out of sync.

**Comment by lcerrato** [comment]
﻿I recommend the borrow/only version to match the header. I checked this when creating the metadata and we do it elsewhere. Otherwise all of the volumes

**Comment by mkonieczny9805** [comment]
@AlisonBabeu @lcerrato Thank you, yes I will use the editions that match the info in the new CTS files.

**Pull request merged**
