### PR TITLE
Phi0134

### PR DESCRIPTION
**Pull request by zachhimes**
The only files that I have changed since the December edits pull request are in phi0134.phi002-phi006.

### CODE REVIEW

**Comment by lcerrato** [comment]
Hi @zachhimes.

I think something is happening that is causing too many changes in your branch. This is telling me there are 843 changes, which should't be happening if you're only working on a subset of files. 

This looks like it has all of the December edits changes plus the new changes. Perhaps you branched from the December edits branch?

**Comment by lcerrato** [comment]
please also see #135 for more comments

**Comment by zachhimes** [comment]
I'm checking my log file and I think I accidentally merged master with the December edits branch before creating the branch phi0134.

**Comment by PonteIneptique** [comment]
Hey @zachhimes , for the master situation, here's what I would do - if I may : 

- Have upstream set to PerseusDL/canonical-latinLit : `git remote add upstream https://github.com/PerseusDL/canonical-latinLit.git`
- Fetch upstream `git fetch upstream`
- Delete your local master `git branch -D master`
- Create one from the one on upstream `git checkout -b master upstream/master`

I think that normally, when you'll do git pull, you'll have a master depending on upstream :') You can also call it master_perseus and it would be good as well

**Pull request closed without merging**
