### PR TITLE
Quint

### LINKED ISSUE #92: phi1002
I have started the conversion. The files have been cut into book while they should be only apparently. Is there any reason for it ? @AlisonBabeu @balmas @lcerrato 
Catalogs refer to it as a single urn.

http://catalog.perseus.org/catalog/urn:cts:latinLit:phi1002.phi001

### PR DESCRIPTION
**Pull request by PonteIneptique**
Fixes #92 

Thanks @zachhimes for the work which made it possible.

### CODE REVIEW

**Comment by balmas** [comment]
@PonteIneptique why no URN bumping here?

**Comment by PonteIneptique** [comment]
I decided not to bump urn until we get the catalog working... Same with 0058

**Comment by balmas** [comment]
Hmm. Actually I think the catalog *is* working for this -- just the Perseus 4 files were wrong. We only have the correct URN cataloged for Institutio Oratoria -- urn:cts:latinLit:phi1002.phi001.perseus-lat1.  I'm going to go ahead and reserve the new URN and bump this one.

**Comment by AlisonBabeu** [comment]
Yes, I only cataloged what I assumed would be the correct URN for the
Perseus editions.

**Pull request merged**
