### PR TITLE
Fixed miscellaneous typos in Lucan BC 1

### PR DESCRIPTION
**Pull request by diyclassics**
All corrections checked against Weise's print edition.

### CODE REVIEW

**Comment by balmas** [comment]
Thanks @diyclassics ! @lcerrato whenever you have a minute, can you confirm it's okay to merge?

**Comment by lcerrato** [comment]
Thanks!

**Comment by diyclassics** [comment]
Quick question about contributions to the “Canonical” repository—what is the relationship between the repo and the PDL website? I see my contributions reflected in Github, but not on the website. Are there plans to update the website based on changes in the repo? Thanks, PJB

**Comment by lcerrato** [comment]
Currently the relationship is severed. We cannot host EpiDoc + CTS versions of texts within Perseus 4 (current version of the PDL) so changes to texts in GitHub will not be visible on P4.

Depending on the text, we do make duplicate edits to the PDL version of the file, but I am working towards retiring this practice for minor typos. This is handled via a different workflow apart from GitHub and even when edits are made to a source text, a P4 site build is required to push them out. 

There are tools under development that will allow for browsing the canonical repo versions of texts once they are compliant with the new standards.

**Pull request merged**
