### PR TITLE
(phi1254)(phi1276)

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Updated all cts_.xml files and headers
Updated bibliographic descriptions.

### CODE REVIEW

**Review by lcerrato — APPROVED** [review]

**Comment by lcerrato** [comment]
@AlisonBabeu 
At some point the metadata for phi1276 broke — it was passing and now is not. (All metadata file for both canonical repos should pass).
Be on the lookout for this.

**Comment by lcerrato** [comment]
fix cts via https://github.com/PerseusDL/canonical-latinLit/pull/485

**Comment by AlisonBabeu** [comment]
Will do, what exactly went wrong I wonder or broke?

**Comment by lcerrato** [comment]
“ti:” was missing from the description tag `<ti:description>` versus `<description>`
See
https://github.com/PerseusDL/canonical-latinLit/pull/485/commits/804b5b6518c7ffe123dc77f67671ae7a79d4c485

**Pull request merged**
