### PR TITLE
(phi0474.phi022.perseus-lat1.xml) EpiDoc and CTS conversion

### PR DESCRIPTION
**Pull request by PonteIneptique**
Added a link to the Archive.org resource because I had to check something.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |     0.09 |
| `nodes_count`   |   147    |
| `texts_passing` |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +16948 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi022/phi0474.phi022.perseus-lat1.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5247)*

**Comment by mkonieczny9805** [comment]
FYI @lcerrato @PonteIneptique I start my new position Feb. 16, so, aim to have the Cicero conversion completed by then?

**Comment by lcerrato** [comment]
@mkonieczny9805 
Thanks for the update. We can only do what we can do — however much you contribute before then is very much appreciated.

**Comment by PonteIneptique** [comment]
> FYI @lcerrato @PonteIneptique I start my new position Feb. 16, so, aim to have the Cicero conversion completed by then?
Let's go ;)

**Comment by mkonieczny9805** [comment]
@lcerrato Is `<quote rend="smallcaps">` ok?

**Review by mkonieczny9805 — APPROVED** [review]

**Comment by mkonieczny9805** [comment]
@lcerrato It also looks like I've lost the ability to merge?
Screen Shot 2021-02-01 at 6 35 28 PM

**Comment by lcerrato** [comment]
Hi @mkonieczny9805 
I didn't change any permissions. Very odd.

**Comment by lcerrato** [comment]
@mkonieczny9805 
Yes, those tags should be fine.
If you need to attach your file I can try to merge.

**Comment by lcerrato** [comment]
@mkonieczny9805 
You might want to double check your branch. Maybe you are still on master?

**Comment by mkonieczny9805** [comment]
@lcerrato I can merge again, not sure what happened there. I'll probably be done with this one later in the afternoon. Thanks for your answers to my earlier question too!

**Comment by mkonieczny9805** [comment]
@lcerrato @PonteIneptique 
Any idea what tag to use for something like "Decurionum decreta" in this snippet? It's not exactly a `<quote>`, since it refers to the title of the quoted document and not its actual contents. This type of thing is common in forensic speeches.
Screen Shot 2021-02-02 at 2 15 43 PM

**Comment by lcerrato** [comment]
@mkonieczny9805 It could be `<title rend="smallcaps">`

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |      0.1 |
| `nodes_count`   |    147   |
| `texts_passing` |      1   |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +16942 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi022/phi0474.phi022.perseus-lat1.xml` | Deleted  |
| `./data/phi0474/phi022/phi0474.phi022.perseus-lat2.xml` | New      |
| `./data/phi0474/phi022/phi0474.phi022.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5277)*

**Pull request merged**
