### PR TITLE
 (phi0474.phi035.perseus-lat1.xml) EpiDoc and CTS conversion

### PR DESCRIPTION
**Pull request by PonteIneptique**
If I am not wrong, all old Latin Perseus files of Cicero are now following Capitains guidelines  :)

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |      0.1 |
| `nodes_count`   |    558   |
| `texts_passing` |      1   |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +53425 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi035/phi0474.phi035.perseus-lat1.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5271)*

**Comment by mkonieczny9805** [comment]
Sorry guys, I don't think I'm going to have the mental fortitude to verify all the section breaks here, it's a really long text.

**Comment by lcerrato** [comment]
@mkonieczny9805 No problem. Just do what you can and I'll bump to a different issue or review when the PR is ready.

**Comment by PonteIneptique** [comment]
Anyhow, I just want to thank you for the support @mkonieczny9805 :)
And obviously @lcerrato ;)

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |     0.09 |
| `nodes_count`   |   558    |
| `texts_passing` |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |   +53426 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/phi0474/phi035/phi0474.phi035.perseus-lat1.xml` | Deleted  |
| `./data/phi0474/phi035/phi0474.phi035.perseus-lat2.xml` | New      |
| `./data/phi0474/phi035/phi0474.phi035.perseus-lat2.xml` | Passing  |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5312)*

**Pull request merged**
